### ISSUE TITLE
To-do list

### ISSUE THREAD

**Issue by harsh212** [AyushWebDev/ResumeMakerCumPortfolio#7]
@AyushWebDev 

- [x] Pull and test new changes #6 
- [x] Give front-end Design for employer  Page
- [x] Push backend changes.

@harsh212 

- [x] Pull backend changes after @AyushWebDev  commit.
- [x] Implementation of employer page after getting design from @AyushWebDev
